### ISSUE TITLE
Data Creating Method

### ISSUE THREAD

**Issue by amirgholami** [jayroxis/PINNs#1]
Hey Jay,

Thanks so much for creating this repository. It is quite helpful. I was wondering how you created the "burgers_shock.mat" data? Is this data computed by analytically solving the Burgers equation? Would it be possible to have the code you used to generate that?

Best,
-Amir

**Comment by jayroxis** [comment]
Hi Amir,

The code in this repository is just the exact translation of the [original PINN](https://github.com/maziarraissi/PINN) from TensorFlow v1 to PyTorch. All the data are directly copied from the original work. Actually, I've tried to wrote an implementation myself that samples points from ICs and BCs and it worked perfectly. Practically, you don't need a stored data like the original work, you can generate those points in your Python training code.

**Comment by amirgholami** [comment]
That makes sense, thanks for converting the code to pytorch, it is very userful
