### ISSUE TITLE
Unable to visualize data in test code

### ISSUE THREAD

**Issue by michaeljehan** [jayroxis/PINNs#2]
<img width="1111" alt="Screen Shot 2021-10-18 at 4 11 53 PM" src="https://user-images.githubusercontent.com/68639241/137702675-3685324d-586f-4b7e-8c39-4458f574688b.png">
I am currently trying out the Burgers Identification (PyTorch) code, however, It was able to train, but I cannot visualize the result. Any suggestionn on how to fix it?
Thanks

**Comment by jayroxis** [comment]
The visualization of text uses LaTex. Did you have it installed?
If it doesn't work, you can try to remove the Tex rendering.

**Comment by jayroxis** [comment]
The latex rendering configuration can be found in line 22-23 at `Utilities/plotting.py`. Remove these two lines:
```python
    "pgf.texsystem": "pdflatex",        # change this if using xetex or lautex
    "text.usetex": True,                # use LaTeX to write all text
```

**Comment by soren-hub** [comment]
@michaeljehan If you use version 3.1.2 of matplotlib the problem disappears.

> ` pip install matplotlib==3.1.2 `
