### ISSUE TITLE
Burgers inference discrete time

### ISSUE THREAD

**Issue by reyhashemi** [jayroxis/PINNs#3]
Hi @jayroxis and thank you very much for this useful repository, really appreciated.

I was wondering if by any chance your pytorch implementation for the Burgers Equation inference solution, **"time discrete"** approach was also available and open to public?

Thank you again!

PS: sorry for asking this in an issue, I could not find your email.

**Comment by jayroxis** [comment]
Hi @reyhashemi,

I haven't got chance to implement it, since I think it would be easy to adapt the continuous version to discrete version.

**Comment by reyhashemi** [comment]
Thank you Jay! Please share with us in the case you would do it some day ! your codes are neat and I learned a lot. :)
