### ISSUE TITLE
In the function 'loss_func' of 'Net class' of"Burgers.ipynb", do we need to add 'self.adam.zero_grad()' ?

### ISSUE THREAD

**Issue by kl869994854** [jayroxis/PINNs#6]
In the function 'loss_func' of 'Net class' of"Burgers.ipynb", do we need to add 'self.adam.zero_grad()' ?

**Comment by jayroxis** [comment]
Yes, you are right. It is actually a bug, I fixed now, thanks a lot for pointing out.
